### ISSUE TITLE
For MIUI 12 of whyred (Redmi Note 5), please.

### ISSUE THREAD

**Issue by 1457384613gh** [gursewak10/wifi_extender#3]
For MIUI 12 of whyred (Redmi Note 5), please.
It can work but MIUI 12.
Please upgrade for MIUI 12.
![Screenshot_2021-08-11-11-13-38-014_com android updater](https://user-images.githubusercontent.com/69227436/128964144-bce67b9a-2723-4e34-91ba-12030b42f0db.jpg)
![Screenshot_2021-08-11-11-13-50-868_com android settings](https://user-images.githubusercontent.com/69227436/128964153-f34df35c-a1e1-4e07-9240-c07d57e2f595.jpg)

**Comment by yangmeishu** [comment]
youtube 搜索 wifi hotspot same miui 播放最多那个， 亲测可以
